sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install -g npm@^2.0.0
before_script:
  - npm prune
node_js:
  - "4.1"
after_success:
  - npm run semantic-release
script:
  - npm run test
